spring:
  application:
    name: base_spring_boot

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TicketBooking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Duc17072005@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 864000

cloudinary:
  cloud_name: dmnhhykeg
  api_key: 414185256892539
  api_secret: I04ZFI8sFODtDpoThybOQejd1uo

vnpay:
  tmn-code: "14ZGLC9Q"
  hash-secret: "E82E76M9CI1UYH5OFWQY03L2JNNAGGMO"
  payment-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: http://localhost:8082/api/v1/payments/vnpay-return
  ipn-url: "https://c4d0d0eb0c02.ngrok-free.app/api/v1/payments/vnpay-ipn"
  api-url: "https://sandbox.vnpayment.vn/merchantv2/"


---
spring:
  config:
    activate:
      on-profile: booking
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: payment
server:
  port: 8082

springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operationsSorter: alpha
      tagsSorter: alpha
      docExpansion: none
      displayRequestDuration: true
      defaultModelsExpandDepth: 1
      defaultModelExpandDepth: 1
      filter: true
      tryItOutEnabled: true
      persistAuthorization: true



