spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TicketBooking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Duc17072005@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 864000

cloudinary:
  cloud_name: dmnhhykeg
  api_key: 414185256892539
  api_secret: I04ZFI8sFODtDpoThybOQejd1uo

zalopay:
  app-id: 554
  key1: 8NdU5pG5R2spGHGhyO99HN1OhD8IQJBn
  key2: uUfsWgfLkRLzq6W2uNXTCxrfxs51auny
  create-order-url: "https://sb-openapi.zalopay.vn/v2/create"
  callback-url: "https://8cb3abc8d337.ngrok-free.app/api/v1/payments/zalopay-callback"


---
spring:
  config:
    activate:
      on-profile: booking
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: payment
server:
  port: 8082