spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TicketBooking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Duc17072005@
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 864000

server:
      port: 8081

cloudinary:
  cloud_name: dmnhhykeg
  api_key: 414185256892539
  api_secret: I04ZFI8sFODtDpoThybOQejd1uo
